[package]
name = "rawposix"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.4"
dashmap = "5.0"      
once_cell = "1.18" 
libc = "0.2"
parking_lot = "0.12"
tracing = "0.1" 
tracing-subscriber = "0.3"
fdtables = { path = "../fdtables" }
sysdefs = { path = "../sysdefs" }
typemap = { path = "../typemap" }
cage = { path = "../cage" }
threei = { path = "../threei" }
lind-perf = { path = "../lind-perf", optional = true }

[features]
default = ["fast"]
fast = []
secure = []
lind_perf = ["dep:lind-perf", "threei/lind_perf", "fdtables/lind_perf"]

[dev-dependencies]
